name: api_consumption
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

executables:
  apiConsumption: main

dependencies:
 json_annotation: ^4.8.0
 crypto: ^3.0.2
 dio: ^5.0.2

 #di
 get_it: ^7.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
